### ISSUE TITLE
Windows support in the future

### ISSUE THREAD

**Issue by steskalja** [kevinlawler/kerf1#11]
Are there any plans to support windows, and I don't mean with a Linux container?

**Comment by kevinlawler** [comment]
I'm not sure what's involved anymore, actually. It is probably a good project to identify what the list of current incompatibilities is.

I think the major differences would be around `mmap` and anything that is strongly POSIX and not C. My wild guess would be that it is relatively easy (as far as ports go) to get it working on Windows excluding any kind of filesystem support, and progressively more difficult as you as you attempt to match 100% feature parity with respect to written files.

I think WSL2 support is now live, and Kona didn't have much trouble being ported to Cygwin, so those are alternatives prior to full Win32/Win64 support.

I am willing to assist others here but I don't have much expertise in Windows specifics like `CreateFileMappingW`.

As a comparison, I think this migration process should be easier in kerf2 because it avoids some of the more "non-portable" (let's say) functionality of `mmap` and similarly powerful POSIX calls. It is also in C++ and earlier in development, and both of those things help.

**Comment by kevinlawler** [comment]
This is open-ended so I'm closing it.
